- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
     - name: installing multiple servers
       yum:
         name: "{{ item }}"
         state: present
       loop:
          - mysql
       service:
          name: mysql
          state: started
