- hosts: all
  remote_user: ec2-user
  become: yes
  vars:
     mysql_root_password: "Corp@257@"
     port: 3306
  tasks:
     - name: install mysql
       yum:
          name:
            - MySQL-python
            - mysql
            - mysql-server
          state: latest
     - name: start mysql
       service:
          name: mysqld
          enabled: true
          state: started 
    
    

